# Change the look of Adwaita, with ease
# Copyright (C) 2022 Gradience Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Scripts are created by @dominichayesferen for Gradience Team


name: Generate preset lists

on:
  push:
    branches: [ "next" ]
  schedule:
    - cron:  '0 0,12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Run the script
        run: python3 scripts/update-curated.py && python3 scripts/update-official.py
      - name: Commit report
        run: |
          git config --global user.name 'Gradience Team'
          git config --global user.email 'AdwCustomizerTeam@proton.me'
          git commit -am "ci: Generate preset lists"
          git push
